run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    # - staticcheck (panics)
    - structcheck
    # - stylecheck (panics)
    # - typecheck (fails in lots of places)
    - unconvert
    # - unused (panics)
    - unparam
    - varcheck

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.85
