run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
#     - errcheck
    - exportloopref
#     - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - structcheck
#    - stylecheck # seems redundant with revive, which replaced golint
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 15
  revive:
    rules:
    - name: var-naming
      arguments:
      - [ "ID", "API", "JSON" ] # AllowList
      - [ ] # DenyList

issues:
  exclude-rules:
    - linters:
        - revive
      text: "don't use leading"
