steps:
- name: "gcr.io/cloud-builders/git"
  args: [fetch, --tags, --depth=100]
- name: "goreleaser/goreleaser:v0.120.3"
  entrypoint: /bin/sh
  args: ["releasing/cloudbuild.sh", "pluginator"]
  secretEnv: ['GITHUB_TOKEN']
secrets:
- kmsKeyName: projects/jregan-corp-gke-dev/locations/global/keyRings/kust-cloud-key-ring/cryptoKeys/kust-cloud-key-name
  secretEnv:
    GITHUB_TOKEN: CiQAwfbOkSP4tJf3ZJZMjzHaRPZ2RxiQhORZ3xxlVtpoy8631uQSUACk6WMKjtkpsRkRl+uxWUVvN29M5qveyXjaDDO094/qwsSc8RiYlHYt7Ii1bWkkz3P1kG0nHfG7Fd46A+GJ6R5NhmNfingd/nu9iKrNwLXK
