# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

run:
  deadline: 5m
  skip-dirs:
    - yaml/internal/k8sgen/pkg
    - internal/forked

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
#    - errcheck
    - exportloopref
#    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - structcheck
#    - stylecheck # seems redundant with revive, which replaced golint
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 30
  revive:
    rules:
    - name: var-naming
      arguments:
      - [ "ID", "API", "JSON" ] # AllowList
      - [ ] # DenyList
  gosec:
    config:
      G306: "0644"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "don't use leading"
    - linters:
        - staticcheck
      text: "SA1019: kioutil.Legacy"
